### ISSUE TITLE
Fix Home Page CSS

### ISSUE THREAD

**Issue by medunn626** [medunn626/Capstone_Front-End#6]
Currently it is not working correctly

**Comment by medunn626** [comment]
Current CSS:
```CSS
.cn-container{
	width: 60%;
	min-width: 300px;
	max-width: 820px;
	margin: 10px auto 0 auto;
	text-align: left;
  text-transform: uppercase;
	position: relative;
}

h2 {
  display: block;
  font-weight: normal;
  margin: 0;
  padding: 0;
}

.cn-container h2 {
	font-family: 'Arial Narrow';
	color: #fff;
	position: absolute;
	z-index: 1000;
	text-shadow:
		0 0 1px rgba(255,255,255,0.8),
		1px 1px 1px rgba(0,0,0,0.2);
	font-size: 40px;
	line-height: 80px;
	top: 0px;
	right: 0px;
	white-space: nowrap;
	/*opacity: 0;
	transform: scale(0);*/
	transition: all 0.3s linear 0.4s;
}

.cn-container .cn-slide:target h2 {
	opacity: 1;
  right: 0px;
	/*transform: scale(1);*/
}

.cn-slide{
	text-align: center;
	position: absolute;
	/*left: 0px;*/
	padding-top: 80px;
	margin: 0 5%;
	width: 90%;
	/*opacity: 0;*/
  transition: left 0.4s linear, opacity 0.4s linear;
}
.cn-slide:target{
  left: 0px;
	opacity: 1;
	/*z-index: 1000;*/
}

div {
  padding: 0;
  display: block;
  font-weight: 400;
  font-size: 15px;
  color: #391b27;
}

nav {
  display: block;
}

a {
  text-decoration: none;
  cursor: auto;
}

.cn-slide nav a{
	text-align: left;
	/*display: block;*/
	font-family: 'Arial Narrow';
	border: 8px solid #fff;
	padding: 2%;
	font-size: 40px;
	letter-spacing: 7px;
	text-shadow: 0px 5px 0px rgba(182,105,135,0.4);
	color: rgba(255,255,255,0.9);
	line-height: 66px;
	outline: none;
	margin: 0 0 10px 0;
	box-shadow: 1px 1px 3px rgba(0,0,0,0.1);
	background: #fff url("../../Cards_FullRes_white.jpg") no-repeat center center;
	background-size: 100%;
	background-clip: padding-box;
	/*opacity: 0;*/
	transform: scale(0);
	/*transition:
		opacity 0.4s linear,
		transform 0.4s linear,
		box-shadow 0.3s ease-in-out;*/
  transition: all 0.3s ease-in-out;
}

.cn-slide nav a:hover{
	box-shadow: 1px 2px 4px rgba(0,0,0,0.25);
  text-shadow: 1px 1px 1px rgba(0,0,0,0.1);
  color: rgba(255,255,255,0.9);
}

.cn-slide:target nav a{
	opacity: 1;
	transform: scale(1);
}

.cn-slide nav a:nth-child(2){
	transition-delay: 0.3s, 0.3s, 0s;
}
.cn-slide nav a:nth-child(3){
	transition-delay: 0.6s, 0.6s, 0s;
}
.cn-slide nav a:nth-child(4){
	transition-delay: 0.9s, 0.9s,0s;
}

.cn-slide-sub nav a{
	width: 42%;
	display: inline-block;
	font-size: 40px;
}

.cn-slide-sub nav a:nth-child(odd){
	margin-right: 5px;
}

.cn-back{
	outline: none;
	text-indent: -9000px;
	width: 49px;
	height: 42px;
	background: transparent url("../../arrow.png") no-repeat center center;
	position: absolute;
	top: 22px;
	left: -100px;
	cursor: pointer;
	opacity: 0;
	transition: all 0.4s ease-in-out 1s;
}
.cn-slide:target .cn-back{
	left: 3px;
	opacity: 1;
}

/* Main Items */
.cn-slide nav a[href="#slide-1"]{
	background-image: url("../../Cards_FullRes_white.jpg");
}

.cn-slide nav a[href="#slide-2"]{
	background-image: url("../../writing_hands.png");
}

.cn-slide nav a[href="auth/change-password"]{
	background-image: url("../../my-account.jpg");
}

@media screen and (max-width: 1060px){
	.cn-slide-sub nav a{
		font-size: 28px;
	}
}
@media screen and (max-width: 900px){
	.cn-container h2{
		font-size: 48px;
		line-height: 95px;
	}
	.cn-slide nav a{
		font-size: 38px;
	}
	.cn-slide-sub nav a{
		width: auto;
		font-size: 36px;
		display: block;
	}
	.cn-slide-sub nav a:nth-child(odd){
		margin-right: 0px;
	}
}
```

**Comment by medunn626** [comment]
Updated code:

```CSS
.cn-container{
  top: 4%;
  left: 15%;
	width: 100%;
  min-width: 600px;
	max-width: 820px;
	margin: 10px auto 0 auto;
  text-transform: uppercase;
	position: fixed;
  height: auto;

}

h2 {
  display: block;
  font-weight: normal;
  margin: 0;
  padding: 0;
}

.cn-container h2 {
	font-family: 'Arial Narrow';
	position: absolute;
	z-index: 1000;
	text-shadow:
		0 0 1px rgba(255,255,255,0.8),
		1px 1px 1px rgba(0,0,0,0.2);
	font-size: 40px;
	line-height: 80px;
	top: 0px;
  left: 25%;
	white-space: nowrap;
}

.cn-container .cn-slide:target h2 {
	opacity: 1;
  right: 0px;
}

.cn-slide{
	text-align: center;
	position: absolute;
	padding-top: 80px;
	margin: 0 5%;
	width: 100%;
  transition: left 0.4s linear, opacity 0.4s linear;
}

.cn-slide:target{
  left: 0px;
	opacity: 1;
}

a {
  text-decoration: none;
  cursor: auto;
}

.cn-slide nav a{
	text-align: left;
	font-family: 'Arial Narrow';
	border: 8px solid #fff;
	padding: 2%;
	font-size: 40px;
	letter-spacing: 7px;
	color: rgba(0,0,0,0);
	line-height: 100px;
	outline: none;
	margin: 0 0 10px 0;
	box-shadow: 1px 1px 3px rgba(0,0,0,0.1);
	background: #fff no-repeat center center;
	background-size: 100%;
	background-clip: padding-box;
	transform: scale(0);
  transition: all 0.3s ease-in-out;
}

.cn-slide nav a:hover{
	box-shadow: 1px 2px 4px rgba(0,0,0,0.25);
  text-shadow: 1px 1px 1px rgba(0,0,0,0.1);
  color: rgba(255,255,255,1);
  font-weight: bold;
}

/* Main Items */
.cn-slide nav a[href="cards"]{
	background-image: url("../../Cards_FullRes_white.jpg");
}

.cn-slide nav a[href="cards/new"]{
	background-image: url("../../writing_hands.png");
}

.cn-slide nav a[href="auth/change-password"]{
	background-image: url("../../my-account.jpg");
}

@media screen and (max-width: 600px){
	.cn-container h2{
		font-size: 48px;
		line-height: 95px;
	}
	.cn-slide nav a{
		font-size: 38px;
	}
}
```
